### ISSUE TITLE
Global functions should be write protected

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/grpconst#3]
While submitting https://github.com/gap-packages/qpa/issues/27, I've discovered this:
```
gap> ReducedList:=1;                                                  
1
```
This is very unsafe.

**Comment by sunnyquiver** [comment]
I have only changed the name to ReducedListQPA and nothing else.  Then this happens:
```
gap> ReducedListQPA := 1;
Error, Variable: 'ReducedListQPA' is read only
not in any function at line 2 of *stdin*
you can 'return;' after making it writable`
```

Is this fixing the problem?

**Comment by olexandr-konovalov** [comment]
`ReducedListQPA` fixes https://github.com/gap-packages/qpa/issues/27. The problem in this issue is to be addressed in `GrpConst`. Otherwise, a user code may easily overwrite a _function_  `ReducedList` by another value.
